### ISSUE TITLE
Update plugin in gradle plugin site

### ISSUE THREAD

**Issue by DeathGOD7** [vanniktech/gradle-maven-publish-plugin#762] opened 2024-04-22 12:50 UTC
Please update the plugin version in the gradle plugin site too.
Seems the github gradle workflow can't find the newest version.

**Steps:**
1. Have plugins imported in your build file
```
plugins { 
	id("java")
	id("maven-publish")
	id("signing")
	id("com.github.johnrengelman.shadow") version "8.1.1"
	id("com.vanniktech.maven.publish") version "0.28.0"
}
```
2. Use gradle workflow that will build the project
3. Voila... Error!!

Current Version says 0.28.0 but it is 0.13.0 there.
**Source :** [Site](https://plugins.gradle.org/plugin/com.vanniktech.maven.publish)

**Error :** 
```
 Could not resolve com.vanniktech:gradle-maven-publish-plugin:0.28.0.
     Required by:
         project : > com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin:0.28.0
      > No matching variant of com.vanniktech:gradle-maven-publish-plugin:0.28.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.7' but...
 
  ```

**Comment by gabrielittner** [comment] 2024-05-01 07:50
The plugin is currently only published to maven central, to use it make sure maven central is specified in your plugin repositories in `settings.gradle`
```
pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}```

Closing this as duplicate of #669

**Closed by gabrielittner** 2024-05-01 07:50 UTC
