### ISSUE TITLE
CI build broken with 0.9.0: Cannot perform signing task ':signArchives' because it has no configured signatory

### ISSUE THREAD

**Issue by akarnokd** [vanniktech/gradle-maven-publish-plugin#114] opened 2020-02-10 10:10 UTC
After bumping the plugin version to 0.9.0, all my project builds on CI is broken. For example, https://github.com/akarnokd/RxJavaExtensions/pull/51/files . I don't use CI to deploy the artifacts and with 0.8.0, it was expectedly [saying](https://travis-ci.org/akarnokd/RxJavaExtensions/builds/640798449#L205) `:signArchives SKIPPED`. Is there a new settings to skip signing in case of missing keys on CI?

```
$ ./gradlew assemble
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
> Task :signArchives FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```

https://travis-ci.org/akarnokd/RxJavaExtensions/builds/648234157#L202

**Comment by gabrielittner** [comment] 2020-02-10 10:56
I'll take a look later today, thanks for reporting it

**Comment by vanniktech** [comment] 2020-02-10 11:34
Have you tried?

```
mavenPublish {
  releaseSigningEnabled = false
}
```

**Comment by akarnokd** [comment] 2020-02-10 11:52
Wouldn't that disable signing when I do want to release from my local build?

**Comment by gabrielittner** [comment] 2020-02-10 18:45
This is caused by removing our hacky `onlyIf` in #101 which was checking if there are any upload tasks in the task graph.

There is a gradle property you can set for `releaseSigningEnabled`. It's called `RELEASE_SIGNING_ENABLED`. You can set it to false in the committed `gradle.properties` in your repo and then set it to true in the same place where you set the signing properties on your local machine. Does that work for you?

**Comment by akarnokd** [comment] 2020-02-10 18:52
I only want the plugin to sign the jars when I call `uploadArchives`. Every other case, CI or local machine, should not sign them. 0.8.0 worked so far thus I otherwise don't really need to update right now.

**Comment by gabrielittner** [comment] 2020-02-10 19:20
I did a quick check and Gradle seems to do the right thing when using `maven-publish`. So setting 
```
mavenPublish {
	useLegacyMode = false
}
```
should do what you want (for Android projects this requires Android Gradle Plugin 3.6.0).


Another alternative would be setting `RELEASE_SIGNING_ENABLED` to false in your repo and when you publish you run `uploadArchives -PRELEASE_SIGNING_ENABLED=true`.

**Comment by vanniktech** [comment] 2020-02-23 12:35
Is there anything else that we need to do here?

**Comment by gabrielittner** [comment] 2020-02-23 12:50
I don't think so. The only thing we could do as adding back the hack we had before for legacy mode, but I'd like to avoid that and there are work arounds through properties. With AGP 3.6.0 stable being very close I'd just leave it and then we can disable legacy mode by default for the correct behavior.

**Comment by akarnokd** [comment] 2020-02-23 13:24
I'll stay on 0.8.0 for now.

**Comment by vanniktech** [comment] 2020-02-23 13:47
I don't think David is using the Android Gradle Plugin though. So that would not help him

**Comment by gabrielittner** [comment] 2020-02-23 14:24
When me turn off legacy mode by default it will help everyone. It's just Android that's blocking it right now

**Comment by bnvinay92** [comment] 2020-02-23 17:12
Setting the gradle property `RELEASE_SIGNING_ENABLED=false` does not work for me.
Setting the flag no longer generates the `signArchives` task but instead I get this error:

```
Execution failed for task ':workflow-rx2:uploadArchives'.
> Could not publish configuration 'archives'
   > Unable to generate signature for '/Users/Vinay/AndroidStudioProjects/careem-workflow/kotlin/workflow-rx2/build/poms/pom-default.xml' as no signatory is available to sign
```

**Comment by vanniktech** [comment] 2020-03-21 16:18
We can close this given that #120 was merged, right?

**Comment by gabrielittner** [comment] 2020-03-21 16:49
Yes

**Closed by gabrielittner** 2020-03-21 16:49 UTC

**Comment by gabrielittner** [comment] 2020-03-24 17:57
@akarnokd 0.10.0 should work for you again without having to configure anything
